on: push
name: ğŸŸ£ Codechecks

jobs:
    build-and-codechecks:
        name: build and run codechecks
        runs-on: ubuntu-latest
        steps:
            - name: ğŸ‘ Checkout
              uses: actions/checkout@master

            - name: ğŸ“¥ Install Dependencies
              run: yarn install --frozen-lockfile

            - name: ğŸ” Run Codechecks
              run: npx codechecks
              env:
                  CC_SECRET: ${{ secrets.CC_SECRET }}
